### ISSUE TITLE
Calling autogen.sh fails if /bin/sh != /bin/bash

### ISSUE THREAD

**Issue by linuxrrze** [suse-samba-tools/admin-tools#2]
autogen.sh is executed in /bin/sh, but uses BASH variables.

On systems where sh != bash (like Ubuntu) this will fail.

Easy fix: Replace /bin/sh with /bin/bash in first line

**Comment by dmulder** [comment]
Thanks for catching that.

**Comment by dmulder** [comment]
Fixed in 4298f68

**Comment by linuxrrze** [comment]
Hi,

i heard about that tool just yesterday on Samba XP conference and I'm still struggling to get it compiled on Ubuntu.
Once I get it done there may be more fixes ;-)

That tool really is kind of a "missing link" between the automation possibilities of samba-tool and the Windows GUI tools.

Thanks for developing it!
 Marcel
May 29, 2020 3:01 PM, "David Mulder" <notifications@github.com (mailto:notifications@github.com?to=%22David%20Mulder%22%20<notifications@github.com>)> wrote:
	Thanks for catching that.

**Comment by dmulder** [comment]
FYI, I'm working on a branch which removes all the yast dependencies for the build (see my libyui-bindings branch). It's still a ways out, but this will *hugely* simplify the build (only libyui to build + install some python scripts).

**Comment by linuxrrze** [comment]
Sounds great! Looking forward to that.

Right now I'm testing the AppImage version, and I'd like to give some feedback/suggestions for improvement.
What's your preferred way to do that?

Should I open issues (or one issue for all), or just send them to you via PM?

**Comment by dmulder** [comment]
I'd say open individual issues here, then I can track when things are fixed, etc.
