### ISSUE TITLE
IPv6 reverse zones are listed as "Forward lookup zones"

### ISSUE THREAD

**Issue by linuxrrze** [suse-samba-tools/admin-tools#4]
My ipv6 reverse zones are displayed under
    "Forward Lookup Zones"
but they should be listed unter
    "Reverse Lookup Zones"

Example:
   1.2.3.4.5.6.7.8.9.a.b.c.1.0.a.2.ip6.arpa

**Comment by dmulder** [comment]
lol, I'll take a look.

**Comment by dmulder** [comment]
I can't duplicate this. Maybe I fixed it? I can't remember.
@linuxrrze feel free to reopen this if you are still seeing this problem on the latest admin-tools.
