### ISSUE TITLE
Reference to libyui @ f3ca12c broken

### ISSUE THREAD

**Issue by linuxrrze** [suse-samba-tools/admin-tools#6]
You seem to be referencing an old ref of the libyui repo.

So build fails when calling `git submodule update` which fails with "not our ref".

**Comment by dmulder** [comment]
> git --version
git version 2.33.0

I don't see the same issue. Maybe you have a git version that doesn't support branch tracking?
Take a look at the .gitmodule file. It's pointed at master branches, not at a specific commit hash.

**Comment by dmulder** [comment]
I posted I didn't see the issue, but simply didn't fail until later. I'll look into it.

**Comment by dmulder** [comment]
If you look at the .gitmodule file, I'm fetching master branches, not a specific commit. So this message is confusing.

**Comment by dmulder** [comment]
I believe I've resolved the issue. So, despite the .gitmodule tracking the master branch, git still commits a hash for the initial checkout (I suppose prior to checking out the specified branch). It seems libyui has rewritten their git history, erasing that old HEAD commit (which no one should ever do, but anyway). So I've commited a new commit hash which should permit the checkout to succeed.
